pipeline {
    agent {
        label 'devops'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        TF_IN_AUTOMATION = '1'  // Prevent Terraform from prompting
    }
    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git url: 'https://github.com/kailash-Prajapati/Jenkins.git', branch: 'terraformdeploy'
            }
        }

        // // Uncomment these if SonarQube analysis is needed
        // /*
        // stage('Sonarqube Analysis') {
        //     steps {
        //         dir('terraform/') {
        //             withSonarQubeEnv('sonar-scanner') {
        //                 sh '''
        //                 $SCANNER_HOME/bin/sonar-scanner \
        //                 -Dsonar.projectName=terraform-ci-secure \
        //                 -Dsonar.projectKey=terraform-ci-secure
        //                 '''
        //             }
        //         }
        //     }
        // }

        // stage('QualityGate') {
        //     steps {
        //         script {
        //             waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
        //         }
        //     }
        // }

        // stage('OWASP Scan') {
        //     steps {
        //         dir('terraform/') {
        //             dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-check'
        //             dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
        //         }
        //     }
        // }
        

        stage('Terraform Init') {
            steps {
                dir('terraform/') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform/') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('terraform/') {
                    sh 'terraform apply --auto-approve'
                }
            }
        }

        stage('Terraform Destroy') {  // Fixed stage name and syntax
            steps {
                dir('terraform/') {
                    sh 'terraform destroy --auto-approve'  // Fixed command
                }
            }
        }
    }
}
